### ISSUE TITLE
Using Security component

### ISSUE THREAD

**Issue by gauravmak** [hashmode/VisualCaptcha-Cakephp-Plugin#2]
As imageField and audioField are being set only if Security component is present, should the installation process specify to add it to the components array if it is not added already?

**Comment by hashmode** [comment]
AFA i understood you meant to add those fields into unlocked field list only if it has not been added yet. If so, yes, that might be a good idea, but i guess would not be a big deal even if it is added and it adds again. Please feel free to make pull request if you can. thanks

**Comment by gauravmak** [comment]
No, I didn't mean that. Check #3 please.

**Comment by hashmode** [comment]
Ok, got it, you are write. Thanks for the pull request - merged
